apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: invoiceservice
    version: "1.0"
  name: invoiceservice
  namespace: pitstop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: pitstop
        app: invoiceservice
        version: "1.0"
    spec:
      containers:
      - env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        image: pitstop/invoiceservice:1.0
        imagePullPolicy: IfNotPresent
        name: invoiceservice
      restartPolicy: Always
