apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    system: pitstop
    app: notificationservice
    version: "1.0"
  name: notificationservice
  namespace: pitstop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        system: pitstop
        app: notificationservice
        version: "1.0"
    spec:
      containers:
      - env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        image: pitstop/notificationservice:1.0
        imagePullPolicy: IfNotPresent
        name: notificationservice
      restartPolicy: Always
