apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: workshopmanagementapi
    system: pitstop
    version: "1.0"
  name: workshopmanagementapi
  namespace: pitstop
spec:
  replicas: 1
  selector: null
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: workshopmanagementapi
        system: pitstop
        version: "1.0"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: pitstop/workshopmanagementapi:1.0
        imagePullPolicy: IfNotPresent
        name: workshopmanagementapi
        ports:
        - containerPort: 5200
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  labels:
    system: pitstop
    app: workshopmanagementapi
    version: "1.0"
  name: workshopmanagementapi
  namespace: pitstop
spec:
  type: NodePort
  ports:
  - name: "http-5200"
    port: 5200
    targetPort: 5200
    nodePort: 30007
  selector:
    system: pitstop
    app: workshopmanagementapi
    version: "1.0"
---
